name: Deploy MedSense HMI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Show runner info
        run: |
          whoami
          hostname
          pwd

      - name: Deploy on delta
        run: |
          cd /srv/stacks/MedSense_Docker_App_EE
          git fetch origin
          git reset --hard origin/main
          docker compose up --build -d